name: Python CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest

    - name: Run Tests
      run: pytest

# Uncomment the following section to enable Docker build and push to Docker Hub
#-------------------------------------------------- |

# name: CI & Docker Build

# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

# jobs:
#   test:
#     name: 🧪 Run Python Tests
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4

#       - name: Set up Python
#         uses: actions/setup-python@v5
#         with:
#           python-version: '3.11'

#       - name: Install dependencies
#         run: |
#           pip install --upgrade pip
#           pip install -r requirements.txt
#           pip install pytest

#       - name: Run pytest
#         run: pytest

#   docker:
#     name: 🐋 Build & Push Docker Image
#     needs: test
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4

#       - name: Log in to Docker Hub
#         uses: docker/login-action@v2
#         with:
#           registry: docker.io
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_TOKEN }}

#       - name: Build Docker image
#         run: |
#           docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/salamanet-showcase:${{ github.sha }} .
#           docker tag ${{ secrets.DOCKERHUB_USERNAME }}/salamanet-showcase:${{ github.sha }} \
#                      ${{ secrets.DOCKERHUB_USERNAME }}/salamanet-showcase:latest

#       - name: Push to Docker Hub
#         run: |
#           docker push ${{ secrets.DOCKERHUB_USERNAME }}/salamanet-showcase:${{ github.sha }}
#           docker push ${{ secrets.DOCKERHUB_USERNAME }}/salamanet-showcase:latest
